---
- name: test
  shell: echo $USER;
  register: shell_result
- debug:
    var: shell_result.stdout_lines

- name: add cert-manager repo from git
  shell: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml

- name: add cluster role
  shell: |
         kubectl create clusterrolebinding cluster-admin-binding \
         --clusterrole=cluster-admin \
         --user=admin

- name: check cert-manager
  shell: kubectl get pods --namespace cert-manager

- name: prepare issuer prod
  template: src=issuer-prod.yaml.j2 dest=~/issuer-prod.yaml

- name: prepare issuer staging
  template: src=issuer-staging.yaml.j2 dest=~/issuer-staging.yaml

- name: adding issuers
  shell: kubectl apply -f ~/issuer-prod.yaml && kubectl apply -f ~/issuer-staging.yaml

  