---
- name: start rke
  shell: |
        docker run -d --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        --privileged \
        rancher/rancher:latest
        --acme-domain {{ rancher_domain }}