---
- name: start rancher dashboard
  shell: |
        docker run -d --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        --privileged --name rancher \
        rancher/rancher:v2.5-head \
        --acme-domain {{ rancher_domain }}