---
- name: copy cluster.yml
  template: src=cluster.yml.j2 dest=~/cluster.yml

- name: start rke
  shell: |
        rke up --config ~/cluster.yml && \
        echo "KUBECONFIG=/root/kube_config_cluster.yml" >> /etc/environment

- name: check cluster
  shell: kubectl get nodes

- name: remove ingress nginx webhook service
  shell: kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission